### ISSUE TITLE
Move sending

### ISSUE THREAD

**Issue by jwilson780** [ModelTwelve/TCPChess#7]
I updated the code to handle castling.  It works in theory and the moves list now handles it but when I try to run the program it keep sending the move as "MOVE,to,to", where to is the move I chose.  What is should send is "MOVE,from,to".  I am thinking it is a client issue, possibly with the awesome new setup where it shows moves.  It does this for all pieces.  I am gonna look into it more when I get up tomorrow morning.  You can see where I highlighted it in the error messages
@ModelTwelve @cvgresch93 
![movissue](https://cloud.githubusercontent.com/assets/6071372/14911269/599afb26-0dc2-11e6-8e00-5b0f9d13ab8f.JPG)

**Comment by ModelTwelve** [comment]
It would shock me if the client was guilty ... after all ... it would initially let you move any piece to anywhere! Heck ... it would let you move a clients piece! None of that code should be different ... it's all up to the moves action in the server to decide.

I tried to take a peek but a pull didn't give me any new code?

Can you push the code changes you're testing so I can give it a go on my side?

**Comment by ModelTwelve** [comment]
Ok ... this was me! Hooray! I inspected the POSSIBLE code and saw that I was reusing a class level var to show the boxes to move to but that var is supposed to remember which piece was last selected.

Code pushed but not much tested.
